name: Playwright Tests
run-name: "${{ github.event_name == 'workflow_dispatch' && format('Manual: {0}', inputs.test_type) || github.event_name == 'schedule' && 'Nightly Regression Run' || format('Automated Smoke Test: {0}', github.event_name) }}"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Select a test suite to run manually'
        required: true
        default: 'Regression'
        type: choice
        options:
          - Smoke
          - Regression

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
    
    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Smoke Tests (Push / PR)
      if: |
        github.event_name == 'push' || 
        github.event_name == 'pull_request' || 
        (github.event_name == 'workflow_dispatch' && inputs.test_type == 'smoke')
      run: npm run test:smoke

    - name: Run Full Regression Tests (Nightly / Manual)
      if: |
        github.event_name == 'schedule' || 
        (github.event_name == 'workflow_dispatch' && inputs.test_type == 'regression')
      run: npm test
    
    - name: Checkout gh-pages
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages-dir

    - name: Allure Report Action
      uses: mgrybyk-org/allure-report-branch-action@v1
      if: always()
      continue-on-error: true
      id: allure
      with:
        report_id: 'self-test'
        gh_pages: 'gh-pages-dir'
        report_dir: 'allure-results'

    - name: Git Commit and Push Action
      uses: mgrybyk-org/git-commit-pull-push-action@v1
      if: always()
      with:
        repository: gh-pages-dir
        branch: gh-pages
        pull_args: --rebase -X ours
    
    - name: Send Email Notification
      uses: dawidd6/action-send-mail@v4
      if: always()
      with:
        server_address: ${{ secrets.SMTP_SERVER }}
        server_port: ${{ secrets.SMTP_PORT }}
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: 'Playwright API Test Run: ${{ job.status }}'
        to: mr.mp.shaw.1983@gmail.com 
        from: Playwright Automation Bot <mr.mp.shaw.1983@gmail.com>
        secure: true
        content_type: text/html
        html_body: |
          <p>Playwright opencart test suite execution completed with status: <strong>${{ job.status }}</strong></p>
          
          <p>You can view the full interactive dashboard here: 
          <a href="${{ steps.allure.outputs.report_url }}">
            View Allure Test Report
          </a></p>
          
          <p>Triggered by event: <strong>${{ github.event_name }}</strong> by <strong>${{ github.actor }}</strong> on branch ${{ github.head_ref || github.ref_name }}.</p>